;
(function(){
	   var app=angular.module('szgw.cotroller',[]);
	   //index页面的控制器
	   app.controller('indexCtrl',function($scope,$rootScope,$window){
	   	 //下面导航的数据
	   	   $scope.navs=[
	   	        {
	   	        	name:'首页',
	   	        	id:'1',
	   	        	src:'img/fz.png',
	   	        	url:'#/index/one'
	   	        },{
	   	        	name:'VIP',
	   	        	id:'2',
	   	        	src:'img/vip.png',
	   	        	url:'#/index/two'
	   	        },{
	   	        	name:'广播',
	   	        	id:'3',
	   	        	src:'img/gb.png',
	   	        	url:'#/index/three'
	   	        },{
	   	        	name:'购物车',
	   	        	id:'4',
	   	        	src:'img/car.jpg',
	   	        	url:'#/index/four'
	   	        },{
	   	        	name:'我的',
	   	        	id:'5',
	   	        	src:'img/1.gif',
	   	        	url:'#/index/five'
	   	        }
	   	    ];
	   	  //点击下面的导航栏进行跳转
	   	  $rootScope.id=1;
	   	  $scope.Toggle1=function(id,url){
	   	  	     $rootScope.id=id;
	   	  	     $window.location.href=url;
	   	  }
	   });
	   app.controller('oneCtrl',function($scope,$rootScope,$window){
	   	//搜索框的部分
	   	     $scope.searchName='';
	  	      $scope.isSearch=false;
	  	      $scope.search=function(){
	  	      	      $scope.isSearch=true;
	  	      }
	  	      $scope.cancelSearch=function(){
	  	      	      $scope.isSearch=false;
	  	      }
		   	//商品列表导航
		   	$scope.navs1=[
		   	        {
		   	        	name:'商场',
		   	        	id:'1',
		   	        	url:'#/index/goodList'
		   	        },{
		   	        	name:'商圈',
		   	        	id:'2',
		   	        	url:'#/index/goodList'
		   	        },{
		   	        	name:'超市',
		   	        	id:'3',
		   	        	url:'#/index/goodList'
		   	        },{
		   	        	name:'美食',
		   	        	id:'4',
		   	        	url:'#/index/goodList'
		   	        },{
		   	        	name:'头条',
		   	        	id:'5',
		   	        	url:'#/index/goodList'
		   	        },{
		   	        	name:'沃超市',
		   	        	id:'6',
		   	        	url:'#/index/goodList'
		   	        },{
		   	        	name:'附近',
		   	        	id:'7',
		   	        	url:'#/index/goodList'
		   	        },{
		   	        	name:'我喜欢',
		   	        	id:'8',
		   	        	url:'#/index/goodList'
		   	        }
		   	]
		   	$scope.navs2=[
		   	        {
		   	        	name:'特惠',
		   	        	id:'1',
		   	        	url:'#/index/goodList'
		   	        },{
		   	        	name:'本周新品',
		   	        	id:'2',
		   	        	url:'#/index/goodList'
		   	        },{
		   	        	name:'天天特价',
		   	        	id:'3',
		   	        	url:'#/index/goodList'
		   	        },{
		   	        	name:'发现好店',
		   	        	id:'4',
		   	        	url:'#/index/goodList'
		   	        },{
		   	        	name:'精品推荐',
		   	        	id:'5',
		   	        	url:'#/index/goodList'
		   	        },{
		   	        	name:'购物达人',
		   	        	id:'6',
		   	        	url:'#/index/goodList'
		   	        }
		   	]
		   	//点击商品列表
		   	$rootScope.id=1;
	   	    $scope.Toggle2=function(id,url){
	   	  	     $rootScope.id=id;
	   	  	     $window.location.href=url;
	   	  }
	   	    
	   });
	   app.controller('twoCtrl',function($scope){
	   	   
	   });
	   app.controller('threeCtrl',function($scope){
	   	 
	   });
	   app.controller('fourCtrl',function($scope){
	   	   
	   });
	   app.controller('fiveCtrl',function($scope){
	   	       
	   });
	   //one商品分类的子页面
	   app.controller('onelist1Ctrl',function($scope){
	   	
	   })
	   //商品列表页
	   app.controller('goodListCtrl',function($scope,$http){
	   	     //搜索框的部分
	   	     $scope.searchName='';
	  	      $scope.isSearch=false;
	  	      $scope.search=function(){
	  	      	      $scope.isSearch=true;
	  	      }
	  	      $scope.cancelSearch=function(){
	  	      	      $scope.isSearch=false;
	  	      }
	   	     //商品列表页面的信息
	   	     $scope.lists=[];
	   	     $scope.isshow=false;
	   	     var load=function(){
	   	     	$http.get('js/self/goodList.json',{
	   	     	
		   	     }).success(function(data){
		   	     	    console.log(data);
		   	     	    $scope.lists=$scope.lists.concat(data);
		   	     	    console.log($scope.lists);
		   	     	    $scope.isshow=true;
		   	     })
	   	     };
	   	     load(); 
	   	     //加载得太快，"正在加载字样就闪现"
	   	     $scope.loadmore=function(){
	   	     	      $scope.isshow=false;
	   	     	      load();
	   	     }
	   })
})();
